### ISSUE TITLE
Segment idea: list all opened buffers on the bar 

### ISSUE THREAD

**Issue by rochacbruno** [eburghar/kakship#4]
Just like the bufline in vim and helix, it would be nice to create a segment to show opened buffers on the tabline.

The info seems to be available on `%val{buflist}`

Something like

```toml
[custom.kakbuflist]
description = "Open buffers"
format = "[ %val{buflist} ]($style)"
style = "fg:white"
when = ''
shell = ['true']
disabled = false

```

this is how it looks like

![2023-09-19_14-26](https://github.com/eburghar/kakship/assets/458654/fff36137-11ed-4e17-94c8-e2063335399e)

Any idea on how do I make it better?

- format the quoted list returned by `buflist`
- omit the current opened buffer from list, as it already shows on the other segment
- omit the debug buffer
- add a marker to modified buffers

**Comment by rochacbruno** [comment]
Ok, I got something working

```toml
[custom.kakbuflist]
description = "Open buffers"
format = "[ $output ]($style)"
style = "fg:white"
when = 'true'
shell = ['sh']
command = 'kks get -s ${kak_session##*/} %val{buflist} | grep -vE "(\*debug\*|${kak_buffile##*/})" | paste -s -d "|" '
disabled = false
```

requires the installation of  https://github.com/kkga/kks

Looks better now

![kakbuflist](https://github.com/eburghar/kakship/assets/458654/73bcf9f2-17ee-49ef-ad12-de87c964bc2f)
